### ISSUE TITLE
Add cron for utilizing server-sync

### ISSUE THREAD

**Issue by SHU-red** [tmahmood/taskwarrior-web#15]
Seems like cron is not installed on your arch-linux installation

Adding something like (not knowing arch very well)
```bash
pacman -Suy cronie
systemctl enable --now cronie.service
```
could solve it i think?

So then i could add cron-jobs for executing `task sync` and editing `crontab -e` and mount something like:
```
<mount>:/etc/crontabs/
```

Feel free to add this to your example docker compose?!

**Comment by tmahmood** [comment]
Yes, by default, cronie is not installed in Arch Linux. Now added, Let me know if it works properly for you.

**Comment by SHU-red** [comment]
Absolutely no prob
Im very glad you are taking time for this

Love your keyboard-first approach and the lean UI

Slowly trying to integrate it into my environment using a syncchampion server, using cron is a step forward for me

Thank you and im appreciating your awesome work

**Comment by tmahmood** [comment]
Thank you! Really appreciate it. :-) 

I am really glad if this is helping you in way

**Comment by SHU-red** [comment]
Tested your newest release:

```
sh-5.2$ crontab -e
no crontab for task - using an empty one
/bin/sh: line 1: /usr/bin/vi: No such file or directory
crontab: "/usr/bin/vi" exited with status 127
```

I guess
- cronie is now installed
- the default editor is vi
- vi is not installed

So sorry to annoy you again
I think there are two ways:
1. install vi
OR
3. install/use another default editor and change `$EDITOR` variable
My personal preferation would be just to install vi because i like it

But if nano is better for people im also fine with it

**Comment by tmahmood** [comment]
Interesting, I never noticed Arch do not include VI in default installation! Hah. But I can never live without vim, so it's always installed at the very beginning. 

Added VI in the DockerFile.

And no worries! Happy to help!

**Comment by SHU-red** [comment]
Thank you! Now i could

2. add the volume mount to my docker-compose: `<mystuff>/taskwarrior-web_cron:/var/spool/cron/`
3. use `crontab -e` to add e.g. `*/3 * * * * task sync` to sync every 3 minutes (if i did not do a mistake`

But it seems to not work because i do not get an updated version

As i try to use `systemctl status cronie` i get:
```
[task@c27d114a74f4 ~]$ systemctl status cronie
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to system scope bus via local transport: Host is down
```

I am not sure if `systemctl` is needed for `cron`/`cronie` to run but having a look at [this](https://wiki.archlinux.org/title/Cron) source, seems to feel like `systemctl` is needed am i right?

> After installation, the daemon will not be enabled by default. The installed package likely provides a service, which can be controlled by [systemctl](https://wiki.archlinux.org/title/Systemd#Using_units). For example, cronie uses cronie.service.

**Comment by SHU-red** [comment]
Did a bit of research. Instead of taking the effort to add `systemd`, `cron` can also be ran by using `crond` daemon.

This could be added to your `start.sh` as something like:

```
crond -n -s
```

Testing this i got an error like
```
crond: can't open or create /var/run/crond.pid: No such file or directory
```

Guessing this could be caused by crond not having root permissions or something

Sorry for the inconvenience. Its your decision if you want to put time/effort into this

Im not sure if im qualified enough and can spend the time to create a PR myself

**Comment by tmahmood** [comment]
Hey, sorry, I am a bit packed. Will take a look once I am free.

**Comment by SHU-red** [comment]
No hurry
I even could try to make a PR
But spending time is also not easy for me

**Comment by tmahmood** [comment]
I understand, and thank you for taking your time, PR would be welcome. When I can make the change and check (there are few other things broken, that needs fixing too) I will do it myself.

**Comment by monofox** [comment]
In my setup, i have to execute cron jobs as well (i've bugwarrior running). But i solved it differently, as i do not want to let some cronjobs running within the same docker container (i want easily be able to define further and to define which interval, etc.)

For example, my `docker-compose.yml`:

```yaml
services:
  web:
    image: ghcr.io/tmahmood/taskwarrior-web:main
    ports:
      - "127.0.0.1:8090:3000"
    volumes:
      - ./data/env:/app/.env
      - ./data/task:/app/taskdata
      - ./data/taskrc:/app/.taskrc
      - ./data/timewarrior:/app/.timewarrior
      - ./data/bugwarrior/bugwarriorrc:/app/.config/bugwarrior/bugwarriorrc
    environment:
      ...
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      ofelia.enabled: "true"
      ofelia.job-exec.bugwarrior_runner.schedule: "@every 1h"
      ofelia.job-exec.bugwarrior_runner.command: "/bin/bash -c \"bugwarrior pull\""
      ofelia.job-exec.timewjira_runner.schedule: "@every 1h"
      ofelia.job-exec.timewjira_runner.command: "/bin/bash -c \"timew jirapush\""
    restart: always

  ofelia:
    image: mcuadros/ofelia:latest
    restart: always
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    environment:
      - TZ=${TZ}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    depends_on:
      - web
    labels:
      ofelia.enabled: "true"
      com.centurylinklabs.watchtower.enable: "true"
    security_opt:
      - label=disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```

I'm running `bugwarrior pull` and `timew jirapush` each of them as a cronjob every hour with the help of ofelia.

Wouldn't be this the better approach?

**Comment by SHU-red** [comment]
Just to re-update here
Im still on it (if i find time) and my current favourite solution is to just use `watch` command

The great thing is:
- `watch` seems to already be installed
- one-line command like `watch -n 60 task sync` should do its job

The thing is: Using my docker-compose file below for some reason seems to not fire the command since its not updating my tasks in the background. Using `watch -n 60 task sync` manually inside of the containers console works ... so there must be something i oversee at the moment

```yaml
  taskwarrior-web:
    container_name: taskwarrior-web
    image: ghcr.io/tmahmood/taskwarrior-web:main
    network_mode: bridge
    restart: unless-stopped
    command: bash -c "watch -n 60 task sync"
    volumes:
      - /mnt/tank/dvol/taskwarrior-web_data:/app/taskdata
      - /mnt/tank/dvol/taskwarrior-web_config/.taskrc:/app/.taskrc
      - /mnt/tank/dvol/taskwarrior-web_cron:/var/spool/cron/
    ports:
      - 3000:3000
  ```

**Comment by SHU-red** [comment]
Thanks for your advice

I now tested all of those combinations (plus the ones using brackets [] for the commands)

Nothing works ... there must be something obvious i do not see

```yaml
...


    command: watch -n 60 bash -c "/usr/bin/task sync"


    command: bash -c "while true; do /usr/bin/task sync; sleep 60; done"

    command: bash -c "echo '*/60 * * * * /usr/bin/task sync' > /var/spool/cron/cronjobs/$(date +'%Y%m%d') && crontab /var/spool/cron/cronjobs/$(date +'%Y%m%d')"

...
```

**Comment by tmahmood** [comment]
Hey, 

I am also not very well versed with docker, so not sure if I can suggest anything related to it. I really need to get up to the mark with it :)

Do you want something like that, once synced, the UI detects the changes and updates automatically? I have some ideas to implement it, but not getting any time at all to work on this.

**Comment by SHU-red** [comment]
# Update WebUI

> Do you want something like that, once synced, the UI detects the changes and updates automatically?

I do not want to annoy you with this and i absolutely do not need this urgently, but i guess i am not the only one who uses taskwarrior over multiple devices and therefor needs some sort of syncing which changes the current task information

If you are willing to do something like this it would help for the future i guess

---

# Sync

Regarding THIS issue: A good way would be (i guess) to utilize docker environment variables to define wether `task sync` shall be executed

So what ___could___ be done for this issue in your implementation is
1. Check if Environment variable exists e.g.: `TWW_SYNC`
2. If variable exists, cast its value to integer and concurrently execute `do /usr/bin/task sync && echo 'Synced at $(date)'; sleep <TWW_SYNC>; done` in the background

This means if a user specifies its  docker-compse like below, your container automatically would call `task sync` in a defined loop. AFAIK this feels the most docker like, to configure your service via env-vars

```yaml
services:
  taskwarrior-web:
    container_name: taskwarrior-web
    image: ghcr.io/tmahmood/taskwarrior-web:main
    restart: unless-stopped
    environment:
      - TWW_SYNC=60
    volumes:
      - /mnt/tank/dvol/taskwarrior-web_data:/app/taskdata
      - /mnt/tank/dvol/taskwarrior-web_config/.taskrc:/app/.taskrc
      - /mnt/tank/dvol/taskwarrior-web_cron:/var/spool/cron/
    ports:
      - 3000:3000
```
